version: '3'
services:
    mongo-1-2:
        container_name: "mongo-1-2"
        image: mongo
        ports:
            - "30012:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        restart: always

    mongo-1-3:
        container_name: "mongo-1-3"
        image: mongo
        ports:
            - "30013:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        restart: always

    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        links:
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        restart: always

    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: mongo
        depends_on:
            - "mongo-1-1"
        links:
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-1-1
            - MONGO2=mongo-1-2
            - MONGO3=mongo-1-3
            - RS=rs1
        entrypoint: [ "/scripts/setup.sh" ]

    mongo-2-2:
        container_name: "mongo-2-2"
        image: mongo
        ports:
            - "30042:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017
        restart: always

    mongo-2-3:
        container_name: "mongo-2-3"
        image: mongo
        ports:
            - "30043:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017
        restart: always

    mongo-2-1:
        container_name: "mongo-2-1"
        image: mongo
        ports:
            - "30041:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017
        links:
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        restart: always

    mongo-rs2-setup:
        container_name: "mongo-rs2-setup"
        image: mongo
        depends_on:
            - "mongo-2-1"
        links:
            - mongo-2-1:mongo-2-1
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-2-1
            - MONGO2=mongo-2-2
            - MONGO3=mongo-2-3
            - RS=rs2
        entrypoint: [ "/scripts/setup.sh" ]


    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mongo
        ports:
            - "30002:27017"
        command: mongod --replSet cnf-serv --rest --configsvr --port 27017
        restart: always

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: mongo
        ports:
            - "30003:27017"
        command: mongod --replSet cnf-serv --rest --configsvr --port 27017
        restart: always

    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mongo
        ports:
            - "30001:27017"
        command: mongod --replSet cnf-serv --rest --configsvr --port 27017
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        restart: always

    mongo-cnf-setup:
        image: mongo
        depends_on:
            - "mongo-cnf-1"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "/scripts/setup_cnf.sh" ]

    mongo-router:
        container_name: "mongo-router"
        image: mongo
        ports:
            - "27017:27017"
        depends_on:
            - "mongo-cnf-1"
            - "mongo-1-1"
            - "mongo-2-1"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
            - mongo-2-1:mongo-2-1
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        command: mongos --configdb cnf-serv/mongo-cnf-1:27017,mongo-cnf-2:27017,mongo-cnf-3:27017
        restart: always

    mongo-shard-setup:
        image: mongo
        depends_on:
            - "mongo-router"
        links:
            - mongo-router:mongo-router
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGOS=mongo-router
            - MONGO11=mongo-1-1
            - MONGO12=mongo-1-2
            - MONGO13=mongo-1-3
            - MONGO21=mongo-2-1
            - MONGO22=mongo-2-2
            - MONGO23=mongo-2-3
            - RS1=rs1
            - RS2=rs2
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: [ "/scripts/init_route.sh" ]
        restart: on-failure:20

